name: GitHub Actions Build
run-name: ${{ github.actor }} is testing Plan9Port out from GitHub Actions ğŸš€
on: [push]
jobs:
  Build-on-Ubuntu:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install build deps
        run: sudo apt install build-essential xorg-dev
      - name: Build p9p
        run: ./INSTALL
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  Build-on-macOS:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build p9p
        run: ./INSTALL
      - run: echo "ğŸ This job's status is ${{ job.status }}."
